### ISSUE TITLE
On newer android this package is causing my app to crash.

### ISSUE THREAD

**Issue by IvRRimum** [xxsnakerxx/react-native-flurry-analytics#16]
```
09-01 09:42:08.916 2216-2241/com.adpages.android E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                                   Process: com.adpages.android, PID: 2216
                                                                   java.lang.NullPointerException: Null context
                                                                       at com.flurry.android.FlurryAgent.init(SourceFile:330)
                                                                       at com.flurry.android.FlurryAgent.a(SourceFile:6158)
                                                                       at com.flurry.android.FlurryAgent$Builder.build(SourceFile:1552)
                                                                       at com.xxsnakerxx.flurryanalytics.FlurryAnalyticsModule.startSession(FlurryAnalyticsModule.java:45)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
                                                                       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
                                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                       at java.lang.Thread.run(Thread.java:761)
```

My package.json

```
{
  "name": "MyApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "runiPhone5s": "react-native run-ios --simulator=\"iPhone 5s\""
  },
  "dependencies": {
    "@exponent/react-native-action-sheet": "^0.2.1",
    "@remobile/react-native-refresh-infinite-listview": "github:remobile/react-native-refresh-infinite-listview#pull/8/head",
    "react": "15.4.1",
    "react-mixin": "^2.0.2",
    "react-native": "0.38.0",
    "react-native-animation": "^1.0.6",
    "react-native-barcode-scanner-universal": "^1.0.5",
    "react-native-communications": "^2.1.0",
    "react-native-fetch-blob": "^0.10.4",
    "react-native-flurry-analytics": "^1.0.3",
    "react-native-gifted-listview": "github:faridsafi/react-native-gifted-listview#pull/51/head",
    "react-native-loading-container": "^0.4.0",
    "react-native-mail": "^1.5.0",
    "react-native-maps": "^0.12.2",
    "react-native-onesignal": "^1.2.3",
    "react-native-permissions": "git+https://github.com/alextkd/react-native-permissions.git",
    "react-native-share": "^1.0.13",
    "superagent": "^3.1.0"
  }
}
```

**Comment by IvRRimum** [comment]
Someone here? Still relevant..

**Comment by neuberoliveira** [comment]
iam having this same issue, so [i make a fork](https://github.com/neuberoliveira/react-native-flurry-analytics) and do some changes in native code.

For me its working now, no more Null Context, if anyone confirm the fix i can do a pull request.

Put this answer in #5 too.

**Comment by vinceprofeta** [comment]
@neuberoliveira Is this still an issue?
