### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Null context

### ISSUE THREAD

**Issue by dvolland** [xxsnakerxx/react-native-flurry-analytics#5]
Getting the following exception in my Crashlytics logs: Any ideas what is causing this and if it is a problem?

```
Fatal Exception: java.lang.NullPointerException: Null context
       at com.flurry.android.FlurryAgent.init(SourceFile:302)
       at com.flurry.android.FlurryAgent.a(SourceFile:6139)
       at com.flurry.android.FlurryAgent$Builder.build(SourceFile:1529)
       at com.xxsnakerxx.flurryanalytics.FlurryAnalyticsModule.startSession(FlurryAnalyticsModule.java:45)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:158)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by xxsnakerxx** [comment]
Any updates on this? Is it still happens?

**Comment by IvRRimum** [comment]
@xxsnakerxx Confirmed on OREO: https://github.com/xxsnakerxx/react-native-flurry-analytics/issues/16

**Comment by neuberoliveira** [comment]
iam having this same issue, so [i make a fork](https://github.com/neuberoliveira/react-native-flurry-analytics) and do some changes in native code.

For me its working now, no more Null Context, if anyone confirm the fix i can do a pull request.

**Comment by fschai89** [comment]
I also get report for Crashlytics
```
Fatal Exception: java.lang.NullPointerException: Null context
       at com.flurry.android.FlurryAgent.init(SourceFile:318)
       at com.flurry.android.FlurryAgent.a(SourceFile:6146)
       at com.flurry.android.FlurryAgent$Builder.build(SourceFile:1498)
       at com.xxsnakerxx.flurryanalytics.FlurryAnalyticsModule.startSession(FlurryAnalyticsModule.java:43)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:163)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:760)
```

Device: Redmi Note 4
OS: Android 7.0
